MrCMS.Web/Areas/Admin/Models/UserSubscriptionReports/UserSubscriptionReportsSearchQuery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MrCMS.Web.Areas.Admin.Models.UserSubscriptionReports
{

    public class UserSubscriptionReportsSearchQuery
    {
        private DateTime _startDate;
        private DateTime _endDate;

        public UserSubscriptionReportsSearchQuery()
        {
            _startDate = DateTime.MinValue;
            _endDate = DateTime.MinValue;
        }

        [Required(ErrorMessage = "*start date")]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public DateTime StartDate
        {
            get
            {
                if (_startDate == DateTime.MinValue)
                {
                    _startDate = new DateTime(DateTime.Now.Year, 1, 1);
                    return _startDate.Date;
                }
                else
                    return _startDate;
            }
            set
            {
                _startDate = value;
            }
        }
        [Required(ErrorMessage = "*end date")]
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public DateTime EndDate
        {
            get
            {
                if (_endDate == DateTime.MinValue)
                {
                    _endDate = DateTime.Now;
                    return _endDate.Date;
                }
                else
                    return _endDate;
            }
            set
            {
                _endDate = value;
            }
        }
    }
}

MrCMS.Web/Areas/Admin/Controllers/UserSubscriptionReportsController.cs
using System.Web.Mvc;
using MrCMS.ACL.Rules;
using MrCMS.Entities.People;
using MrCMS.Models;
using MrCMS.Services;
using MrCMS.Web.Areas.Admin.Helpers;
using MrCMS.Web.Areas.Admin.ModelBinders;
using MrCMS.Web.Areas.Admin.Models;
using MrCMS.Web.Areas.Admin.Services.UserSubscriptionReports;
using MrCMS.Website;
using MrCMS.Website.Binders;
using MrCMS.Website.Controllers;
using System.Collections.Generic;
using MrCMS.Web.Areas.Admin.Models.UserSubscriptionReports;
using MrCMS.Web.Areas.Admin.ACL.UserSubscriptionReports;
using Newtonsoft.Json;

namespace MrCMS.Web.Areas.Admin.Controllers
{
    public class UserSubscriptionReportsController : MrCMSAdminController
    {
        private readonly IUserSubscriptionReportsService _userSubscriptionReportsService;

        public UserSubscriptionReportsController(IUserSubscriptionReportsService userSubscriptionReportsService)
        {
            _userSubscriptionReportsService = userSubscriptionReportsService;
        }

        [MrCMSACLRule(typeof(UserSubscriptionReportsACL), UserSubscriptionReportsACL.View)]
        public ViewResult Index(UserSubscriptionReportsSearchQuery searchQuery)
        {
            return View(searchQuery);
        }

        [MrCMSACLRule(typeof (UserSubscriptionReportsACL), UserSubscriptionReportsACL.View)]
        public JsonResult GraphData(UserSubscriptionReportsSearchQuery searchQuery)
        {
            var data = _userSubscriptionReportsService.GetAllSubscriptions(searchQuery);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

MrCMS.Web/Areas/Admin/Views/UserSubscriptionReports/Index.cshtml
@using MrCMS.Helpers
@model MrCMS.Web.Areas.Admin.Models.UserSubscriptionReports.UserSubscriptionReportsSearchQuery

@{
    ViewBag.Title = @Resource("Admin User Subscription Reports Title", "User Subscription Reports");
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string xAxisLabel = @Resource("User Subscription Tooltip Title X", "Subscribed On");
    string yAxisLabel = @Resource("User Subscription Tooltip Title Y", "Number of Users");
    string graphLabel = @Resource("User Subscription Graph Label", "User Subscriptions Per Month");
}

@using (Html.BeginForm("Index", "UserSubscriptionReports", FormMethod.Get))
{
    <fieldset>
        <legend>
            @Resource("Admin User Subscription Reports (Monthly) Title", "User Subscription Reports (Monthly)")
            <span class="btn-group display-inline pull-right">
                <input type="submit" class="btn btn-primary" value="@Resource("Range Filter")" />
            </span>
        </legend>

        <div class="row">
            <div class="col-lg-8"></div>
            <div class="col-lg-2">
                @Html.LabelFor(query => query.StartDate)
                @Html.TextBoxFor(query => query.StartDate, new { @class = "date-time-picker form-control" })
            </div>
            <div class="col-lg-2">
                @Html.LabelFor(query => query.EndDate)
                @Html.TextBoxFor(query => query.EndDate, new { @class = "date-time-picker form-control" })
            </div>
        </div>
    </fieldset>


    <div class="row">
        <div class="col-lg-10 col-lg-push-1">
            <div data-d3-graph="@Url.Action("GraphData", "UserSubscriptionReports", new { StartDate = Model.StartDate.ToString(), EndDate = Model.EndDate.ToString() })" data-d3-graph-label="@graphLabel" data-d3-x-axis-label="@xAxisLabel" data-d3-y-axis-label="@yAxisLabel">
                <div class="alert alert-info hidden margin-top-10">
                    <strong>@Resource("Admin User Subscription -  No Data Notification", "There is no data for the selected time period.")</strong>
                </div>
            </div>
        </div>
    </div>
  
}
@{
    Html.IncludeCss("/Areas/Admin/Content/Styles/d3/d3-admin-graph.css");
    Html.IncludeScript("~/Areas/Admin/Content/Scripts/lib/d3/d3.min.js");
    Html.IncludeScript("~/Areas/Admin/Content/Scripts/lib/d3/d3.tip.js");
    Html.IncludeScript("~/Areas/Admin/Content/Scripts/mrcms/line-graph.js");
}