MrCMS.Web/Areas/Admin/Controllers/MessageTemplateController.cs
using System.Web.Mvc;
using MrCMS.Helpers;
using MrCMS.Messages;
using MrCMS.Web.Areas.Admin.Helpers;
using MrCMS.Web.Areas.Admin.ModelBinders;
using MrCMS.Web.Areas.Admin.Services;
using MrCMS.Website.Binders;
using MrCMS.Website.Controllers;

namespace MrCMS.Web.Areas.Admin.Controllers
{
    public class MessageTemplateController : MrCMSAdminController
    {
        private readonly IMessageTemplateAdminService _messageTemplateAdminService;

        public MessageTemplateController(IMessageTemplateAdminService messageTemplateAdminService)
        {
            _messageTemplateAdminService = messageTemplateAdminService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(_messageTemplateAdminService.GetAllMessageTemplateTypesWithDetails());
        }

        [HttpGet]
        public ActionResult AddSiteOverride(string type)
        {
            return View(_messageTemplateAdminService.GetNewOverride(type));
        }

        [HttpPost]
        [ActionName("AddSiteOverride")]
        public ActionResult AddSiteOverride_POST(
            [IoCModelBinder(typeof(MessageTemplateOverrideModelBinder))] MessageTemplate messageTemplate)
        {
            if (messageTemplate != null)
            {
                _messageTemplateAdminService.AddOverride(messageTemplate);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeleteSiteOverride(string type)
        {
            return View(_messageTemplateAdminService.GetOverride(type));
        }

        [HttpPost]
        [ActionName("DeleteSiteOverride")]
        public ActionResult DeleteSiteOverride_POST(
            [IoCModelBinder(typeof(DeleteMessageTemplateOverrideModelBinder))] MessageTemplate messageTemplate)
        {
            if (messageTemplate != null)
            {
                _messageTemplateAdminService.DeleteOverride(messageTemplate);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(string type)
        {
            ModelState.Clear();
            MessageTemplate template = _messageTemplateAdminService.GetTemplate(type);
            if (template != null)
            {
                return View(template);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult Edit_POST(
            [IoCModelBinder(typeof(MessageTemplateOverrideModelBinder))] MessageTemplate messageTemplate)
        {
            if (messageTemplate != null)
            {
                _messageTemplateAdminService.Save(messageTemplate);
                TempData.SuccessMessages()
                    .Add(string.Format("{0} successfully edited", messageTemplate.GetType().Name.BreakUpString()));
                return RedirectToAction("Edit", new { type = messageTemplate.GetType().FullName });
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ImportLegacyTemplate(string type)
        {
            return View((object)type);
        }

        [HttpPost, ActionName("ImportLegacyTemplate")]
        public ActionResult ImportLegacyTemplate_POST(string type)
        {
            _messageTemplateAdminService.ImportLegacyTemplate(type);
            return RedirectToAction("Index");
        }
    }
}

MrCMS.Web/Areas/Admin/Views/MessageTemplate/AddSiteOverride.cshtml
@using MrCMS.Helpers
@model MrCMS.Messages.MessageTemplate
@{
    ViewBag.Title = "Add Message Template Site Override";
}

@using (Html.BeginForm("AddSiteOverride", "MessageTemplate", new { TemplateType = Model.GetType().FullName }, FormMethod.Post, new { id = "edit-message-template" }))
{
    <fieldset>
        <legend>
            @string.Format(Resource("Add {0} Override"), Model.GetType().Name.BreakUpString())
            <span class="pull-right btn-group">
                @Html.ActionLink(Resource("Back"), "Index", "MessageTemplate", null, new { @class = "btn btn-default" })
                <input class="btn btn-primary" type="submit" value="@Resource("Save")" />
            </span>
        </legend>
        @Html.HiddenFor(@base => @base.SiteId)
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.FromAddress)
                    @Html.TextBoxFor(x => x.FromAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.FromAddress)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.FromName)
                    @Html.TextBoxFor(x => x.FromName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.FromName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Cc)
                    @Html.TextBoxFor(x => x.Cc, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Cc)
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.ToAddress)
                    @Html.TextBoxFor(x => x.ToAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ToAddress)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.ToName)
                    @Html.TextBoxFor(x => x.ToName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ToName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Bcc)
                    @Html.TextBoxFor(x => x.Bcc, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Bcc)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    @Html.LabelFor(x => x.Subject)
                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Subject)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    @Html.LabelFor(x => x.Body)
                    @Html.TextAreaFor(x => x.Body, new { @class = (Model.IsHtml ? "ckedit-enabled form-control" : "form-control"), style = "min-height:200px;" })
                    @Html.ValidationMessageFor(x => x.Body)
                </div>
            </div>
        </div>

        <br />

        @Html.InlineCheckboxFor(x => x.IsHtml)
        @Html.InlineCheckboxFor(x => x.IsDisabled)

        @{ Html.RenderAction("Tokens", "MessageTemplateTokens", new { messageTemplate = Model });}
    </fieldset>
}
@{ Html.IncludeScript("~/Areas/Admin/Content/Scripts/mrcms/edit-message-template.js");}

MrCMS.Web/Areas/Admin/Views/MessageTemplate/DeleteSiteOverride.cshtml
@using MrCMS.Helpers
@model MrCMS.Messages.MessageTemplate
@{ Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";}
@using (Html.BeginForm("DeleteSiteOverride", "MessageTemplate", new { TemplateType = Model.GetType().FullName }, FormMethod.Post))
{

    <h1 class="page-header">
        @Resource("Delete Site Override")
        <span class="btn-group  display-inline  pull-right">
            <input type="submit" class="btn btn-danger" value="@Resource("Delete")" />
        </span>
    </h1>

    @Html.InfoBlock(Resource("Warning"), Resource("Admin Message Template Site Override Delete Warning", "Are you sure you want to delete this message template override? This action cannot be undone"), AlertType.danger)
}

MrCMS.Web/Areas/Admin/Views/MessageTemplate/Edit.cshtml
@using MrCMS.Helpers
@model MrCMS.Messages.MessageTemplate
@{
    ViewBag.Title = "Edit Message Template";
    Html.IncludeScript("~/Areas/Admin/Content/Scripts/mrcms/message-template.js");
}

@using (Html.BeginForm("Edit", "MessageTemplate", new { TemplateType = Model.GetType().FullName }, FormMethod.Post, new { id = "edit-message-template" }))
{
    <fieldset>
        <legend>
            @Resource("Edit") @Model.GetType().Name.BreakUpString() (@(Model.SiteId.HasValue ? "Site Override" : "System default"))
            <span class="pull-right btn-group  display-inline ">
                @Html.ActionLink(Resource("Back"), "Index", "MessageTemplate", null, new { @class = "btn btn-default" })
                <input class="btn btn-primary" type="submit" value="@Resource("Save")" />
            </span>
        </legend>
        @Html.HiddenFor(x => x.SiteId)
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.FromAddress)
                    @Html.TextBoxFor(x => x.FromAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.FromAddress)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.FromName)
                    @Html.TextBoxFor(x => x.FromName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.FromName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Cc)
                    @Html.TextBoxFor(x => x.Cc, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Cc)
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(x => x.ToAddress)
                    @Html.TextBoxFor(x => x.ToAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ToAddress)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.ToName)
                    @Html.TextBoxFor(x => x.ToName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.ToName)
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Bcc)
                    @Html.TextBoxFor(x => x.Bcc, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Bcc)
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                @Html.InfoBlock(Resource("Heads up" + "!"), "To send to multiple email addresses via To, Cc or Bcc, separate them with a comma, not a semi-colon")
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    @Html.LabelFor(x => x.Subject)
                    @Html.TextBoxFor(x => x.Subject, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Subject)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    @Html.LabelFor(x => x.Body)
                    @Html.TextAreaFor(x => x.Body, new { @class = (Model.IsHtml ? "message-ckedit form-control" : "form-control"), style = "min-height:200px;" })
                    @Html.ValidationMessageFor(x => x.Body)
                </div>
            </div>
        </div>
        @Html.InlineCheckboxFor(x => x.IsHtml)
        @Html.InlineCheckboxFor(x => x.IsDisabled)

        @{ Html.RenderAction("Tokens", "MessageTemplateTokens", new { messageTemplate = Model });}
    </fieldset>
}

MrCMS.Web/Areas/Admin/Views/MessageTemplate/ImportLegacyTemplate.cshtml
@{ Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";}
@using MrCMS.Helpers
@model string
@using (Html.BeginForm("ImportLegacyTemplate", "MessageTemplate", new { type = Model }, FormMethod.Post))
{

    <h1 class="page-header">
        @Resource("Import Legacy Message Template")
        <span class="btn-group  display-inline  pull-right">
            <input type="submit" class="btn btn-primary" value="@Resource("Import")" />
        </span>
    </h1>

    @Resource("Admin Message Template Import Legacy", "Are you sure you want to import the legacy message template? This action cannot be undone.")
}

MrCMS.Web/Areas/Admin/Views/MessageTemplate/Index.cshtml
@using MrCMS.Helpers
@model System.Collections.Generic.List<MrCMS.Web.Areas.Admin.Models.MessageTemplateInfo>
@{
    ViewBag.Title = "Message Templates";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1 class="page-header">@Resource("Admin Message Templates Title", "Message Templates")</h1>
<table class="table table-condensed table-striped">
    <thead>
        <tr>
            <th>
                @Resource("Message template index - Template Type", "Template Type")
            </th>
            <th>
                @Resource("Message template index - System/Site", "System/Site")
            </th>
            <th>
                @Resource("Message template index - Enabled?", "Enabled?")
            </th>
            <th>
                @Resource("Message template index - Actions", "Actions")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Type.Name.BreakUpString()
                </td>
                <td>
                    @(item.IsOverride ? Resource("Site Override") : Resource("System Default"))
                </td>
                <td>
                    @(item.IsEnabled ? Resource("Message Template Enabled", "Enabled") : Resource("Message Template Disabled", "Disabled"))
                </td>
                <td>
                    <div class="btn-group">
                        @*@Html.ActionLink(Resource("Edit"), "Edit", new { type = item.TypeName }, new { @class = "btn btn-default btn-xs" })*@
                        @if (item.LegacyTemplateExists)
                        {
                            @Html.ActionLink(Resource("Import legacy template"), "ImportLegacyTemplate", "MessageTemplate", new { type = item.TypeName }, new { @class = "btn btn-default btn-xs", data_toggle = "fb-modal" })
                        }
                        @if (!item.IsOverride)
                        {
                            @Html.ActionLink(Resource("Add site override"), "AddSiteOverride", "MessageTemplate", new { type = item.TypeName }, new { @class = "btn btn-default btn-xs" })
                        }
                        else
                        {
                            @Html.ActionLink(Resource("Delete site override"), "DeleteSiteOverride", "MessageTemplate", new { type = item.TypeName }, new { @class = "btn btn-default btn-xs", data_toggle = "fb-modal" })
                        }
                        @Html.ActionLink(Resource("Edit"), "Edit", new { type = item.TypeName }, new { @class = "btn btn-default btn-xs" })
                        @if (item.CanPreview)
                        {
                            @Html.ActionLink(Resource("Preview"), "Get", "MessageTemplatePreview", new { type = item.TypeName }, new { @class = "btn btn-xs btn-default" })
                        }
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>