MrCMS.Web/Areas/Admin/Controllers/VersionsController.cs
using System.Web.Mvc;
using MrCMS.Entities.Documents;
using MrCMS.Web.Areas.Admin.Services;
using MrCMS.Website.Controllers;

namespace MrCMS.Web.Areas.Admin.Controllers
{
    public class VersionsController : MrCMSAdminController
    {
        private readonly IDocumentVersionsAdminService _service;

        public VersionsController(IDocumentVersionsAdminService service)
        {
            _service = service;
        }

        public PartialViewResult Show(Document document, int page = 1)
        {
            return PartialView(_service.GetVersions(document, page));
        }

        [HttpGet]
        public PartialViewResult Revert(DocumentVersion documentVersion)
        {
            return PartialView(documentVersion);
        }

        [HttpPost]
        [ActionName("Revert")]
        public RedirectToRouteResult Revert_POST(DocumentVersion documentVersion)
        {
            _service.RevertToVersion(documentVersion);
            return RedirectToAction("Edit", "Webpage", new { id = documentVersion.Document.Id });
        }
    }
}

MrCMS.Web/Areas/Admin/Views/Versions/Revert.cshtml
@model MrCMS.Entities.Documents.DocumentVersion
@{ Layout = "~/Areas/Admin/Views/Shared/_LayoutPopup.cshtml";}
@using (Html.BeginForm("Revert", "Versions", new { id = Model.Id }, FormMethod.Post, new { style = "display:inline;" }))
{
    <fieldset>
        <legend>
            @Resource("Admin Webpage Revert to version", "Revert to version")
            <span class="btn-group display-inline pull-right">
                <input type="submit" class="btn btn-primary" value="@Resource("Revert")" />
            </span>
        </legend>
        <p>@Resource("Admin Webpage Revert Message", "Please confirm that you want to this version of") @Model.Document.Name</p>
    </fieldset>
}

MrCMS.Web/Areas/Admin/Views/Versions/Show.cshtml
@using System.Linq
@using MrCMS.Helpers
@model MrCMS.Web.Areas.Admin.Models.VersionsModel
@if (Model.Items.Any())
{
    <div data-paging-type="async">
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th>@Resource("Created On")
                    </th>
                    <th>@Resource("User")
                    </th>
                    <th>@Resource("Actions")
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var version in Model.Items)
                {
                    <tr>
                        <td>
                            @version.CreatedOn
                        </td>
                        <td>
                            @(version.User != null ? version.User.Email : "")
                        </td>
                        <td>
                            <div class="btn-group">
                                @if (version.AnyDifferencesFromCurrent())
                                {
                                    @Html.ActionLink(Resource("View"), "ViewChanges", "Webpage", new {id = version.Id}, new {data_toggle = "fb-modal", @class = "btn btn-primary btn-xs"})
                                    @Html.ActionLink(Resource("Admin Webpage Version Revert To This", "Revert to this version"), "Revert", "Versions", new {id = version.Id}, new {data_toggle = "fb-modal", @class = "btn btn-warning btn-xs"})
                                }
                                else
                                {
                                    <span>Same as current</span>
                                }
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        @Html.Pager(Model.Items, "Show", i => new { Model.Id, page = i })
    </div>
}
else
{
    <p>@Resource("Admin Webpage Versions None", "No document versions available").</p>
}