MrCMS.Web/Areas/Admin/Controllers/ImportExportController.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using MrCMS.Helpers.Validation;
using MrCMS.Models;
using MrCMS.Website;
using MrCMS.Website.Controllers;
using MrCMS.Services.ImportExport;

namespace MrCMS.Web.Areas.Admin.Controllers
{
    public class ImportExportController : MrCMSAdminController
    {
        private readonly IImportExportManager _importExportManager;

        public ImportExportController(IImportExportManager importExportManager)
        {
            _importExportManager = importExportManager;
        }

        [HttpGet]
        public ActionResult Documents()
        {
            if (TempData.ContainsKey("messages"))
                ViewBag.Messages = TempData["messages"];
            if (TempData.ContainsKey("import-status"))
                ViewBag.ImportStatus = TempData["import-status"];
            if (TempData.ContainsKey("export-status"))
                ViewBag.ExportStatus = TempData["export-status"];
            return View();
        }

        [HttpGet]
        public ActionResult ExportDocuments()
        {
            try
            {
                byte[] file = _importExportManager.ExportDocumentsToExcel();
                TempData["export-status"] = "Documents successfully exported.";
                return File(file, ImportExportManager.XlsxContentType,
                    "MrCMS-Documents-" + DateTime.UtcNow + ".xlsx");
            }
            catch (Exception ex)
            {
                CurrentRequestData.ErrorSignal.Raise(ex);
                TempData["export-status"] =
                    "Documents exporting has failed. Please try again and contact system administration if error continues to appear.";
                return RedirectToAction("Documents");
            }
        }

        [HttpPost]
        public ActionResult ImportDocuments(HttpPostedFileBase document)
        {
            if (document != null && document.ContentLength > 0 &&
                document.ContentType == ImportExportManager.XlsxContentType)
                TempData["messages"] = _importExportManager.ImportDocumentsFromExcel(document.InputStream);
            else
                TempData["import-status"] = "Please choose non-empty Excel (.xslx) file before uploading.";
            return RedirectToAction("Documents");
        }

        [HttpPost]
        public ActionResult ExportDocumentsToEmail(ExportDocumentsModel model)
        {
            try
            {
                _importExportManager.ExportDocumentsToEmail(model);
                TempData["export-status"] = "Documents successfully exported.";
            }
            catch (Exception ex)
            {
                CurrentRequestData.ErrorSignal.Raise(ex);
                TempData["export-status"] =
                    "Documents exporting has failed. Please try again and contact system administration if error continues to appear.";
            }
            return RedirectToAction("Documents");
        }
    }
}

MrCMS.Web/Areas/Admin/Views/ImportExport/Documents.cshtml
@using System.Collections.Generic
@using System.Linq
@using MrCMS.Helpers
@using MrCMS.Models
@using MrCMS.Services.ImportExport
@model MrCMS.Models.ExportDocumentsModel
@{
    ViewBag.Title = "Import/Export Documents";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var result = (ImportDocumentsResult)ViewBag.Messages;

}
<h1 class="page-header">@Resource("Admin Import / Export Documents Title", "Import / Export Documents")</h1>
<div class="row">
    <div class="col-xs-6">
        <div class="btn-group">
            <a href="@Url.Action("ExportDocuments", "ImportExport")" class="btn btn-primary">@Resource("Admin Import / Export Documents Export Button", "Export Documents")</a>
        </div>
    </div>
    <div class="col-xs-6">
        @using (Html.BeginForm("ExportDocumentsToEmail", "ImportExport", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Email)
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
            <button class="btn btn-primary">Export and send via email</button>
        }
    </div>
</div>


@if (ViewBag.ExportStatus != null)
{
    <br />
    <span class="alert alert-info">@ViewBag.ExportStatus</span><div class="clearfix"></div>
}
<hr />
@Html.InfoBlock("", Resource("Admin Import / Export Documents Info", "Import File must be in .xslx format. After clicking on 'Import Documents' any new documents inside file will be added to database and existing ones will be updated with provided values in file."))
<hr />
@using (Html.BeginForm("ImportDocuments", "ImportExport", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label for="document">@Resource("Admin Import / Export Documents Choose Import File Label", "Choose Import File")</label>

    <input type="file" name="document" id="document" />
    <div class="clearfix"></div>
    <br />
    if (result != null)
    {
        foreach (var item in result.Errors)
        {
            <span>
                @string.Format(Resource("Admin Import / Export Documents Choose Import File Errors", "{0} has the following errors"), @item.Key):
            </span>
            <ul>
                @foreach (string error in item.Value)
                {
                    <li>
                        @error
                    </li>
                }
            </ul>
        }
        if (result.Success)
        {
            <div class="alert alert-success">
                @Resource("Admin Import / Export Documents Choose Batch Created", "A batch run was successfully created for the file").
            </div>
        }
    }
    if (ViewBag.ImportStatus != null)
    {
        <div class="alert alert-danger">@ViewBag.ImportStatus</div>
        <div class="clearfix"></div>
    }

    <input type="submit" class="btn btn-primary" value="@Resource("Import Documents")" />
}